
[[_introduction]]
= Introduction

{link_apache_shiro} is a powerful and easy-to-use Java security framework that
performs authentication, authorization, cryptography, and session management.

This plugin enables access control on controller actions via a set of annotations.
Security checks will be performed before an action is invoked. Annotated actions
will be executed if the user meets the security criteria, otherwise execution is
aborted. The plugin assumes sensible defaults where needed but also lets you
customize behavior.

== Usage

Controller actions must be annotated with any of the following annotations

 * `@org.apache.shiro.authz.annotation.RequiresAuthentication` - Requires the
   current Subject to have been authenticated during their current session for
   the annotated class/instance/method to be accessed or invoked.
 * `@org.apache.shiro.authz.annotation.RequiresUser` - Requires the current
   Subject to be an authenticated user during their current session for
   the annotated class/instance/method to be accessed or invoked.
 * `@org.apache.shiro.authz.annotation.RequiresGuest` - Requires the current
   Subject to be a "guest", that is, they are not authenticated or remembered
   from a previous session for the annotated class/instance/method to be
   accessed or invoked.
 * `@org.apache.shiro.authz.annotation.RequiresPermissions` - Requires the
   current executor's Subject to imply a particular permission in order to
   execute the annotated method. If the executor's associated Subject determines
   that the executor does not imply the specified permission, the method will not
   be executed.
 * `@org.apache.shiro.authz.annotation.RequiresRoles` - Requires the currently
   executing Subject to have all of the specified roles. If they do not have the
   role(s), the method will not be executed.

The annotations may be applied at the class level, in which case all actions will
inherit those constraints. Annotations applied to methods/closures override those
applied at the class level, for example

[source,groovy,linenumbers,options="nowrap"]
----
import griffon.core.artifact.GriffonController
import griffon.metadata.ArtifactProviderFor
import org.apache.shiro.authz.annotation.*

@RequiresAuthentication
@ArtifactProviderFor(GriffonController)
class PrinterController {
    @RequiresPermission('printer:print')
    void print() { ... }

    @RequiresRoles('administrator')
    void configure() { ... }
}
----

Anyone making use of `PrinterController` must be aun authenticated user. Everyone
with the permissions `printer:print` may call the `print` action. Only those users
that have been authenticated _and_ posses the `administrator` role are able to
call the `configure` action.

Apache Shiro's {link_java_authentication_guide} presents the basic vocabulary and
behavior required to authenticate a user into the system. In particular, the
`SecurityUtils` class is used to store the current `Subject`. You may also inject
an `Subject` instance, like so

[source,groovy,linenumbers,options="nowrap"]
----
import griffon.core.artifact.GriffonController
import griffon.metadata.ArtifactProviderFor
import org.apache.shiro.authz.annotation.*
import org.apache.shiro.authc.UsernamePasswordToken
import org.apache.shiro.subject.Subject

@RequiresAuthentication
@ArtifactProviderFor(GriffonController)
class LoginController {
    LoginModel model

    @Inject
    private Subject subject

    @RequiresGuest
    void login() {
        UsernamePasswordToken token = new UsernamePasswordToken(
            model.username, model.password)
        subject.login(token)
    }

    @RequiresAuthentication
    void logout() {
        subject.logout()
    }
}
----

The `login` action will be executed when there's no authenticated user while
the `logout` action will be executed only if the user is currently authenticated.
